@startuml
left to right direction
skinparam {
    DefaultFontName Noto Sans CJK JP Black
}

[*] --> レース一覧
レース一覧 --> レース詳細 : 1R~12Rを選択
レース詳細 --> 出走馬詳細 : 出走馬を選択

state レース一覧 {
    [*] --> 直近レース
    直近レース --> 過去レース : カレンダー選択
    直近レース --> 未出走レース : カレンダー選択
}

state レース詳細 {
    [*] --> 出走馬表
    出走馬表 --> 実績タイム順位
    出走馬表 --> 補正タイム順位
    出走馬表 --> 調教情報
    出走馬表 --> 馬場情報
}

@enduml